### ISSUE TITLE
Fly Speed not included?

### ISSUE THREAD

**Issue by KJTailor** [jbhaywood/5e-statblock-importer#10]
Hi,
I was trying to import a 3rd party monster. The monster is supposed to have a flying speed, but when I try to import it, the flying speed is ignored and not included. Attached is the statblock header as I would import it, and a snippet of the statblock as it came out.

As I have just found out, the same is true for burrowing speed, so it seems to affect all speeds other than walking.
Cheers

KEZAI
Medium monstrosity, unaligned
Armor Class 16 (natural armor)
Hit Points 67 (9d8 + 27)
Speed 30 ft., fly 50 ft.
STR DEX CON INT WIS CHA
13 (+1) 18 (+4) 16 (+3) 4 (–3) 12 (+1) 12 (+1)
Damage Immunities fire
Senses blindsight 60 ft., passive Perception 11
Languages —
Challenge 4 (1,100 XP)

![image](https://user-images.githubusercontent.com/87787745/140631411-6904ee59-46ae-4f88-a1cb-cea0ee7877cc.png)

**Comment by jbhaywood** [comment]
Are you using the latest version, 1.2.2? I tried using the same stats you posted and get this...
![image](https://user-images.githubusercontent.com/5131886/140783459-be18faf9-0666-4feb-902d-3becc7e6a2d5.png)

**Comment by KJTailor** [comment]
After making sure I ran it on the most recent version of everything, I tested in a test world without any other mods enabled and it worked just fine, getting the same result as you did, with the fly speed included. Back in my game world, repeating the same thing, resulted in a stat block without flying speed, like before.

Seems it's another mod interfering...
And a quick test revealed it was [Monster Blocks](https://github.com/zeel01/MonsterBlocks) because that seems to prevent it from happening somehow?

Anyways, thanks for your help :)

**Comment by danlite** [comment]
I noticed that the imported special movement speeds include a ` ft.` suffix which causes the numeric field to display as 0.

<img width="497" alt="Screen Shot 2022-05-02 at 8 15 31 PM" src="https://user-images.githubusercontent.com/153104/166346039-b7913cb5-db68-4edc-b423-0a00d662890e.png">

I'm not sure if this is intentional, or if it has any mechanical side-effects within Foundry, but it does differ from the built-in SRD monster speeds, e.g. "40 ft." followed by "Fly 20, Swim 60". Maybe this is related to the way the Monster Blocks module parses movement speeds?

<img width="427" alt="Screen Shot 2022-05-02 at 8 27 19 PM" src="https://user-images.githubusercontent.com/153104/166346443-6564fbd6-6fcf-42fb-b20d-f8676fa4020c.png">

**Comment by jbhaywood** [comment]
@danlite that wasn't quite the problem but it made me take a second look at the code and I got it fixed, so thanks.

Movement speeds other than Walk will show up in the configure panel correctly now with version 1.4.3.
