### ISSUE TITLE
What is this WotC Standard you speak of?  Can't find it anywhere online

### ISSUE THREAD

**Issue by the-real-orson** [jbhaywood/5e-statblock-importer#16]
Brill Haverkos
Medium Human Thief
Armor Class 18 (+2 Leather Armor)
Hit Points 55
Speed 30 ft.
STR
DEX
CON
INT
WIS
CHA
13 (+1) 20 (+5) 16 (+2) 17 (+3) 13 (+1) 15 (+2)
Saving Throws Str +1, Dex +8, Con +2, Int +6, Wis +1, Cha +2,
Skills Acrobatics +11, Deception +5, Insight +4, Investigation +6, Perception +4, Sleight of Hand +8, Stealth +11
Senses passive Perception 14
Languages Common, Orc, Thieve's Cant, Abyssal
CR 7

Sneak Attack.
Add 4d6 dmg to attack if ADV or ally within 5 ft.

Second-Story Work.
Climb at full movement. Add DEX modifier to running jump.

Evasion.
When making a DEX saving throw, take half damage or no damage on success.

Actions
Rapier + 2.
Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 1d8 + 7 piercing damage.

Dagger.
Melee or Ranged Weapon Attack: +8 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 1d4 + 1 piercing damage.

Shortbow.
Ranged Weapon Attack: +8 to hit, range 80/320 ft., one target. Hit: 1d6 + 5 piercing damage.

Bonus Actions
Cunning Action.
Dash, Disengage, or Hide as a bonus action.

Fast Hands.
Make sleight of hand check, use thieves' tools disarm a trap or open a lock, or Use Object.

Reactions
Uncanny Dodge.
when an attacker that you can see hits you with an attack, you can use your reaction to halve the attack's damage against you.

**Comment by jbhaywood** [comment]
I mean the format they use for all monster and NPC statblocks. Every part of it follows the same ordering: name, size, type, alignment, ac, hp, speed, stats, saving throws, skills, senses, languages, challenge, unnamed features including spellcasting, actions, bonus actions, reactions, legendary actions, lair actions, etc. They always use the same words, like "Speed" instead of "Movement" or something. Action blocks always start with a short title followed by a period. Spells are laid out in the same way all the time. All that stuff.

It's not spelled out anywhere as far as I know, but WotC and most third party publishers follow the same format. This tool assumes the pasted in statblock is following it too in order to parse it correctly. If things are in different orders, or even something that seems small like if the title of an action isn't followed by a period, it's not going to know how to handle it. It's surprisingly hard to make a computer parse text in a way that comes naturally to use humans, so the more predictable something is, the easier it is to make a parser for it.

**Comment by the-real-orson** [comment]
Okay, I'm with you.  I thought there ight be something more specific!  Thanks
