### ISSUE TITLE
Feature Suggestion: Option to select custom compendiums when importing

### ISSUE THREAD

**Issue by Max-FM** [jbhaywood/5e-statblock-importer#20]
This is a really cool module! The only major thing missing in my opinion is the option to select which compendiums to use when importing statblocks using your module (e.g. imported spells from D&D Beyond), as the SRD itself is rather limited and items outside the SRD have to be manually added later. I myself use PDF supplements like the Monster Manual Expanded, and it's much quicker to copy/paste the statblock directly into Foundry via your module, rather than manually adding them as a homebrew monster in D&D Beyond and then importing via Mr Primate's ddb-importer module. Also this way you won't need to worry about direct integration with ddb-importer module as mentioned in https://github.com/jbhaywood/5e-statblock-importer/issues/19, as instead, you could just point your module to the created compendiums themselves.

**Comment by jbhaywood** [comment]
Thanks for the kind words. I've thought about a compendium chooser like you say, but didn't at first because I want to keep the module is simple to use as possible. But since you brought it up, let me ask you a couple questions so that I have a better idea of how the option would be used.

Do you have any third party compendiums installed that you'd want to use this option with? I don't even know what compendiums are out there, and I'd want some to test with. I do know about the DDB compendiums, but they're all blank for me so I don't know if they're broken or what.

What would you want the import to bring in from the compendium? Just the icon, like it's doing now for the SRD compendiums, or would you want an option to pull in the compendium item completely instead of using the one from the statblock?

**Comment by Max-FM** [comment]
So in regards to your first question I'm mainly interested in having objects from my DDB compendiums automatically imported into my monster stat block. My particular use case is so that I can automatically import spells outside the SRD, e.g. Wrathful Smite (PHB), Thunderclap (XGtE), Mind Sliver (TCoE), etc. But I think it's worth generalising the imports to items too for completeness' sake.

For items, I think if the attacks are fully described in the stat blocks under the actions heading, then the icon alone is probably the better option, as for example, in the case of Bugbears, they have an extra die of damage that's included directly in the attack damage die that would get missed out if the item itself was directly imported instead. However, for objects like spells included under the spellcasting traits, then the full item would likely have to be imported since no description is included in the statblock. 

Although thinking about it, the new WOTC statblock standards for spellcasting might we potentially see variant damage die for certain spells cast by certain monsters, as offensive spells may be directly described under the actions heading, which means the icon would be the better shout. However, that's an edge case that could be considered later. I was planning on writing a separate issue for compatibility with the new WOTC standards.

**Comment by jbhaywood** [comment]
Alright, I changed it so that it searches all compendiums in [release 1.4.0](https://github.com/jbhaywood/5e-statblock-importer/releases/tag/v1.4.0) now. This is simpler than adding an option choose, and hopefully shouldn't add too much extra time. Let me know how that works for you. About the new statblocks, go ahead and log a new issue if you notice problems with them.
