### ISSUE TITLE
Stats fail to import

### ISSUE THREAD

**Issue by nyxalteria** [jbhaywood/5e-statblock-importer#51]
Hi so I started converting another book and the stats are failing, likely due to how the stats are formatted, this is the statblock and I was just wondering if it was possible to have the importer read this properly and import it.

Kongamato
Huge dragon, neutral
Armor Class: 29 (natural armor +18, Dex +3, size -2)
Hit Points: 261 (18d12+144)
Speed: 40 ft., fly 160 ft. (average)
STR: 30 (+12) DEX: 17 (+3) CON: 26 (+8) INT: 9 (-1) WIS: 14 (+2) CHA: 17 (+3)
Skills: Athletics +20, Intimidation +9, Perception +13, Stealth +7, Survival +13
Damage Resistances: acid, cold, electricity, fire
Damage Immunities: magic sleep, magic paralysis
Condition Immunities: -
Senses: darkvision 60 ft., passive Perception 23
Languages: Draconic
Challenge: 20 (51,200 XP)
Piercing Beak. When the kongamato attempts to damage an object with its beak attack, the attack does double damage and is treated as if it were made with an adamantine weapon for the purposes of overcoming the object's hardness.
Wailing Dive (1/turn). When the kongamato makes a charge while flying or uses its Flyby Attack feat, its body becomes infused with energy, causing its bite attack to deal an extra 2d6 sonic damage on that attack.
Actions
Multiattack. The kongamato makes five attacks: one with its bite, two with its claws, one with its tail slap, and one with its wings.
Bite. Melee Weapon Attack: +20 to hit, reach 15 ft., one target. Hit: 24 (2d10+12) piercing damage plus 10 (2d6) sonic damage.
Claw. Melee Weapon Attack: +20 to hit, reach 10 ft., one target. Hit: 18 (2d8+9) slashing damage.
Tail Slap. Melee Weapon Attack: +20 to hit, reach 15 ft., one target. Hit: 17 (2d6+9) bludgeoning damage.
Wings. Melee Weapon Attack: +20 to hit, reach 10 ft., one target. Hit: 15 (1d8+9) slashing damage.
Breath Weapon (1/turn). The kongamato exhales a cone of sonic energy that is 50 feet long. Each creature in that area must make a DC 20 Dexterity saving throw, taking 49 (14d6) sonic damage on a failed save, or half as much damage on a successful one.

**Comment by jbhaywood** [comment]
The problem is all the colons they put in after armor class, hit points, all the abilities, skills, damage resistances, etc. Adding support for them would make the code more complicated than it really needs to be. That makes it harder to maintain in the long run. If you delete them it imports fine though. That's still going to be faster than creating it from scratch. I did it with this one, like this...

Kongamato
Huge dragon, neutral
Armor Class 29 (natural armor +18, Dex +3, size -2)
Hit Points 261 (18d12+144)
Speed 40 ft., fly 160 ft. (average)
STR 34 (+12) DEX 17 (+3) CON 26 (+8) INT 9 (-1) WIS 14 (+2) CHA 17 (+3)
Skills Athletics +20, Intimidation +9, Perception +13, Stealth +7, Survival +13
Damage Resistances acid, cold, electricity, fire
Damage Immunities magic sleep, magic paralysis
Condition Immunities -
Senses darkvision 60 ft., passive Perception 23
Languages Draconic
Challenge 20 (51,200 XP)
Piercing Beak. When the kongamato attempts to damage an object with its beak attack, the attack does double damage and is treated as if it were made with an adamantine weapon for the purposes of overcoming the object's hardness.
Wailing Dive (1/turn). When the kongamato makes a charge while flying or uses its Flyby Attack feat, its body becomes infused with energy, causing its bite attack to deal an extra 2d6 sonic damage on that attack.
Actions
Multiattack. The kongamato makes five attacks: one with its bite, two with its claws, one with its tail slap, and one with its wings.
Bite. Melee Weapon Attack: +20 to hit, reach 15 ft., one target. Hit: 24 (2d10+12) piercing damage plus 10 (2d6) sonic damage.
Claw. Melee Weapon Attack: +20 to hit, reach 10 ft., one target. Hit: 18 (2d8+9) slashing damage.
Tail Slap. Melee Weapon Attack: +20 to hit, reach 15 ft., one target. Hit: 17 (2d6+9) bludgeoning damage.
Wings. Melee Weapon Attack: +20 to hit, reach 10 ft., one target. Hit: 15 (1d8+9) slashing damage.
Breath Weapon (1/turn). The kongamato exhales a cone of sonic energy that is 50 feet long. Each creature in that area must make a DC 20 Dexterity saving throw, taking 49 (14d6) sonic damage on a failed save, or half as much damage on a successful one.
