### ISSUE TITLE
legendary actions not parsing correctly

### ISSUE THREAD

**Issue by mcabel** [jbhaywood/5e-statblock-importer#55]
Divine strike legendary action did no parse correctly. 

Also a minor issue, spells do not have links (but that may be by design, idk).
Another minor issue, yesterday I made a monk that had 18 dex(+4) but the stat block used a lower AC.

God
Colossal deity, unaligned
Armor Class 22 (divine armor)
Hit Points 605 (70d12 + 150)
Speed 40 ft., fly 120 ft. (hover), swim 60 ft.
STR DEX CON INT WIS CHA
30 (+10) 18 (+4) 22 (+6) 12 (+1) 20 (+5) 18 (+4)
Saving Throws CON +15, WIS +12 (These should always be higher than attribute bonuses)
Skills Perception +12, Religion +9
Damage Resistances Acid, Lightning, Force, Radiant
Damage Immunities Necrotic
Condition Immunities Blinded, Charmed, Deafened, Frightened, Grappled, Incapacitated, Paralyzed, Petrified, Prone, Restrained, Stunned, Unconscious
Senses Truesight 120 ft., passive Perception 22
Languages All
Challenge 30 (155,000 XP)
Divine Presence. All creatures within 60 feet of the God have disadvantage on saving throws against spells and magical effects.
Godly Spellcasting. The God can cast a variety of powerful spells from all spellcasting classes. It uses its Wisdom as the spellcasting ability (spell save DC 20, +12 to hit with spell attacks). It can cast the following spells as 9th-level spells, and does not require material components to cast them: Banishment, Heal, Meteor Swarm, True Resurrection
Legendary Resistance (3/Day). If the God fails a saving throw, it can choose to succeed instead.
Actions
Multiattack. The God makes two attacks with Divine Smite and one attack with Divine Wrath.
Divine Smite. Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 84 (12d12 + 6) radiant damage.
Divine Wrath. Ranged Spell Attack: +12 to hit, range 120 ft., one target. Hit: 90 (13d12 + 6) force damage. The creature must make a DC 19 Constitution saving throw or become paralyzed for 1 minute.
Divine Fury. Line of Divine Energy (60 ft. long, 5 ft. wide). Each creature in the area must make a DC 19 Dexterity saving throw, taking 156 (24d12) radiant damage on a failed save, or half as much damage on a successful one.
Legendary Actions
Divine Strike (Costs 2 Actions). Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 65 (10d10 + 10) slashing damage.
Divine Blessing (Costs 1 Action). DON'T DEAL DAMAGE WITH THIS ACTION. The God bestows a blessing upon an ally within 60 feet, granting them advantage on their next saving throw.
Divine Nova (Costs 3 Actions). The God releases a burst of divine energy in a 30-foot radius. Each creature in that area must make a DC 19 Constitution saving throw, taking 85 (13d12) radiant damage on a failed save, or half as much damage on a successful one. In addition, all creatures of the God's choice that fail the saving throw are stunned for 1 minute.

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/10392829/e60ac387-0208-4f5c-b1ab-581dc9584c93)

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/10392829/d96800db-5289-4c3f-b4be-2ab589467bbb)

**Comment by jbhaywood** [comment]
Version 1.68 should fix Divine Smite not showing up. The issue with the spells is because this statblock doesn't follow the standard formatting for spells. It should be something like...

_Spellcasting. The lich is an 18th-­level spellcaster. Its spellcasting ability is Intelligence (spell save DC 20, +12 to hit with spell attacks). The lich has the following wizard spells prepared:
Cantrips (at will): mage hand, prestidigitation, ray of frost
1st level (4 slots): detect magic, magic missile, shield, thunderwave
2nd level (3 slots): acid arrow, detect thoughts, invisibility, mirror image
3rd level (3 slots): animate dead, counterspell, dispel, magic, fireball_

or...

_Innate Spellcasting. The lamia’s innate spellcasting ability is Charisma (spell save DC 13). It can innately cast the following spells, requiring no material components.
At will: disguise self (any humanoid form), major image
3/day each: charm person, mirror image, scrying, suggestion
1/day: geas_

If you want to open a new issue for the Monk I can look into it. I need the text of the statblock though. Without it there's no way to know why it wasn't using the right AC.
