### ISSUE TITLE
Unable to install module version 1.7

### ISSUE THREAD

**Issue by DiceAndEasy** [jbhaywood/5e-statblock-importer#65]
When installing the module either through The Forge's installer or directly inside Foundry, v1.69 is installed even though I am on Foundry version 11. This is what it looks like in Foundry if you search for the module, showing the latest version is 1.69:
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/86520580/a430ff4b-b448-4547-a784-a32124b399d9)

If I use the link https://github.com/jbhaywood/5e-statblock-importer/blob/main/module.json to try to install, I get the following error in Foundry:
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/86520580/20304c02-cde6-4a6b-aebe-f5a459bd3f0a)

and if I use this link https://github.com/jbhaywood/5e-statblock-importer to try to install, I get the following error in Foundry:
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/86520580/d7e0596d-60c3-4b13-9521-c98028b883f7)

Foundry version: 11.313
Platform: The Forge
Browser: Chrome

**Comment by Stormthirst** [comment]
I was able to uninstall 1.69 and reinstall which gave me 1.7

**Comment by DiceAndEasy** [comment]
The issue still persists for me as described in my original post.

**Comment by jbhaywood** [comment]
As far as I can tell everything is set up the way it's supposed to be to point to the new version and to add support for Foundry v11. It also works locally. I'd suggest asking in the Foundry Discord for help debugging what's going on. Maybe someone can point you to the Forge Discord, if there is one.

**Comment by DiceAndEasy** [comment]
> As far as I can tell everything is set up the way it's supposed to be to point to the new version and to add support for Foundry v11. It also works locally. I'd suggest asking in the Foundry Discord for help debugging what's going on. Maybe someone can point you to the Forge Discord, if there is one.

I reported the issue in The Forge Discord and they are looking into why it's not grabbing the latest version. In the meanwhile, if anyone else using The Forge encounters this issue, you can workaround this issue and install 1.70 as a custom package from https://forge-vtt.com/bazaar from Manifest URL (use https://raw.githubusercontent.com/jbhaywood/5e-statblock-importer/main/module.json and untick Install from the Bazaar if the package is found) and lock it to v1.70 so it doesn't roll back to 1.69.

**Comment by jbhaywood** [comment]
Thanks for the update. Let me know what you find out.

**Comment by jentastic01** [comment]
I'm having the same issue, but my error reads `Failed to install module: ELOOP: too many symbolic links encountered, stat '/forge-vtt/bazaar/modules/5e-statblock-importer/1.7/.gitignore'`

I tried uninstalling, and now cannot reinstall.

**Comment by jbhaywood** [comment]
Sorry, I don't know how the Forge works. I've never used it myself. I don't know why it would be reporting about the .gitingnore file, I'm assume that's a red herring since that file has nothing to do with running the module.

I looked up the general error and it looks like it has to do with NPM (Node Package Manager). I'd bring this up with the Forge crew.

**Comment by DiceAndEasy** [comment]
I've forwarded this info to The Forge team.

**Comment by rikmarais** [comment]
> Sorry, I don't know how the Forge works. I've never used it myself. I don't know why it would be reporting about the .gitingnore file, I'm assume that's a red herring since that file has nothing to do with running the module.
> 
> I looked up the general error and it looks like it has to do with NPM (Node Package Manager). I'd bring this up with the Forge crew.

Hey there @jbhaywood , Phi from Forge here
I apologise for the ELOOP error. That is a result of renaming 1.7 to 1.70 on our side to allow it to appear as the latest version of the module.

I think there was a mixup with versioning somewhere.

https://discord.com/channels/687213225225355296/694659543052976268/1165433496664293398

The issue downstream at the Forge is that 1.69 > 1.7, which means that 1.7 is regarded as the older package. If it was 1.6.9 it would've worked, but I think the version bump from 1.69 to 1.7 might've been unintentional.

If possible, could I please ask you to re-release with 1.70 which will allow users on 1.69 to get an update prompt since the version has increased 🙏 This will also let Forge users get an update prompt to move up from the version which is experiencing the ELOOP error.

If you prefer to stay with 1.7, 1.8 etc, please let us know and we can hide the 1.6x (not 1.6.x) versions which currently would take precedence above that.

**Comment by MaxPat931** [comment]
Can also confirm that updating from 1.69 > 1.7 is blocked in a non-Forge environment (I believe for the same reason as outlined above), but uninstalling/reinstalling does fetch 1.7 as latest

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/86370342/9fe0c892-2807-438d-af7c-fc502e65bcdc)

**Comment by jbhaywood** [comment]
I released a new version, v1.71, that should fix the issue. I was able to update from v1.63 to it, so hopefully that does the trick.
