### ISSUE TITLE
Not importing statblock properly

### ISSUE THREAD

**Issue by Stormthirst** [jbhaywood/5e-statblock-importer#66]
Trying to import the following statblock:

```
Wilbur Tumblefoot
Small humanoid (halfling), neutral good

AC 11
HP 27 (6d6 + 6)
Speed 25 ft

Abilities
Str 10 (+0)
Dex 12 (+1)
Con 12 (+1)
Int 11 (+0)
Wis 13 (+1)
Cha 15 (+2)

Skills
Persuasion +4
Insight +3

Senses
Passive Perception 11

Languages
Common, Halfling

Actions
Unarmed Strike. Melee Weapon Attack +2 to hit, reach 5 ft, one target. Hit 2 (1d4) bludgeoning damage

Inspirational Speech (Recharge 5-6): Wilbur can use his charisma and storytelling skills to inspire his allies. Each friendly creature within 30 feet of him gains advantage on the next attack roll they make.

Biography
Wilbur is a stout halfling with a well-groomed, brown beard and merry blue eyes. He has a welcoming smile that seems to brighten any room. Wilbur typically wears a simple apron over his clothing as he manages the tavern, and a warm smile is a permanent fixture on his face.

Wilbur is known for his jovial and welcoming personality. He's quick to make friends and is an excellent storyteller. He cares deeply for the safety and comfort of his patrons at Willow's Embrace Tavern and is always ready to offer a word of encouragement or share tales of heroism. Wilbur's bravery and unwavering optimism have earned him the trust and admiration of those who frequent his establishment.

```

It's not importing the hit points, and it's not importing the Inspiration Speech.

Also, how do I get it to add the biography section?

**Comment by Stormthirst** [comment]
PS: I'm using Statblock 1.7 and Foundry 11.313

**Comment by jbhaywood** [comment]
The format of the statblock has to match the standard layout set out by WotC in their monster statblocks. This one differs in a number of ways to that. They also don't include a special biography section, so that part isn't supported at all and you'll have to manually add it.

I'd suggest looking at the 5e SRD that you can download [here](https://dnd.wizards.com/resources/systems-reference-document) and making this statblock match the ones in there. If you got this from a third party publisher, maybe contact them and let them know that they aren't following the standard layout.
