### ISSUE TITLE
Doesnt import visions under senses.

### ISSUE THREAD

**Issue by agassparkle** [jbhaywood/5e-statblock-importer#86]
I am using Foundry v11.313 tried to import a statblock, it worked perfect other than the vision under senses.  
I tired your example "Glabrezu" aswell and it didnt have the truesight in the character sheet.

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/20764960/cef19d11-81cb-494e-99bf-4b13120d8804)

**Comment by MaxPat931** [comment]
This should be fixed in the latest version (1.81.9) per #85, please update and test again

**Comment by meta5by5** [comment]
I have the same issue. I'm using v.1.82.00. It also puts entries that should be Features into the Actions section. Also, it doesn't populate the speed.
Orc Berserker
Orc, Lawful Evil
Armor Class 15 (Chain shirt)
Hit Points 90 (12d8 +36)
Speed 30ft
Proficiency +2
STR
DEX
CON
INT
WIS
CHA
20 (+5) 16 (+3) 17 (+3) 8 (-1) 15 (+2) 14 (+2)
Skills Intimidation +4 Athletics +7 Animal Handling +4 Survival +4 Nature +1
Saving Throws Strength +7 Constitution +5 
Senses darkvision 60ft.
Languages Common, Orc
Challenge 4 (1100 XP) 
Actions
Multiattack. The Berserker makes three weapon melee attacks or three ranged attacks.
Greataxe. Melee Weapon Attack +7 to hit, reach 5 ft, one target. Hit 11 (1d12 +5 ) slashing damage, Properties Heavy, Two-handed.
Javelin. Melee Weapon Attack +7 to hit, range 30/120ft, one target. Hit 8 (1d6 +5 ) piercing damage, Properties Thrown range 30/120ft.
Features
Aggressive. As a bonus action, the creature can move up to its speed toward a hostile creature that it can see.
Menacing. You have proficiency in the intimidate skill. (even if DMG didn't say so, all the orcs on MM got intimidation)
Indomitable. The berserker has advantage on saving throws against being frightened.
You are coming with me. When the berserker drops to 0 hit points he can try to make one melee weapon attack as a reaction to one enemy at 5ft of him.

**Comment by MaxPat931** [comment]
@meta5by5 Just curious, what is the source of this statblock?
There's a lot of formatting that is out of the ordinary

There's no Size listed (the second line should start with `Medium`) and there should be a space in between the distance and units for the speed (e.g. `30 ft`)
As for the individual spells, all of them look to be importing fine to me, except some of them in the provided statblock are inaccurate (Counterspell and Stoneskin are one word)
I do not see the spell slots being added for 4th level, the colon is needed after the parenthetical
There should not be a "Features" section, typically features are just placed after the creature data (e.g. after challenge)
The feature `You are coming with me` does get appended to the previous feature because the feature name is just too long, the max is 4 words otherwise it's assumed to be a sentence, it's hard to determine what the right cutoff is there, but most standard creatures dont have long feature names.
Aggressive should be in a `Bonus Actions` section
Weapon damages arent being set because of space prior to the closing parenthesis 

I do see that spellcaster level is not being set, and it is trying to capture some of the xp text as a flee mortals role, but other than that once it's properly formatted it looks fine

Here's a cleaned up version of the statblock that imports well
```
Orc Berserker
Medium Humanoid (Orc), Lawful Evil
Armor Class 15 (Chain shirt)
Hit Points 90 (12d8 +36)
Speed 30 ft
Proficiency +2
STR
DEX
CON
INT
WIS
CHA
20 (+5) 16 (+3) 17 (+3) 8 (-1) 15 (+2) 14 (+2)
Skills Intimidation +4 Athletics +7 Animal Handling +4 Survival +4 Nature +1
Saving Throws STR +7 CON +5
Senses darkvision 60ft.
Languages Common, Orc
Challenge 4 (1100 XP)
Menacing. You have proficiency in the intimidate skill.
Indomitable. The berserker has advantage on saving throws against being frightened.
You are coming with. me. When the berserker drops to 0 hit points he can try to make one melee weapon attack as a reaction to one enemy at 5ft of him.
Spellcasting. The archmage is an 18th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 17, +9 to hit with spell attacks). The archmage can cast disguise self and invisibility at will and has the following wizard spells prepared:

Cantrips: fire bolt,light,mage hand,Prestidigitation,Shocking Grasp
1st level: detect magic, identify, mage armor, Magic Missile
2nd level: Detect Thoughts, Mirror Image, Misty Step
3rd level: counterspell, Fly, lightning bolt
4th level (3 slots): Banishment,Fire Shield,Stoneskin
Actions
Multiattack. The Berserker makes three weapon melee attacks or three ranged attacks.
Greataxe. Melee Weapon Attack +7 to hit, reach 5 ft, one target. Hit 11 (1d12 + 5) slashing damage, Properties Heavy, Two-handed.
Javelin. Melee Weapon Attack +7 to hit, range 30/120ft, one target. Hit 8 (1d6 + 5) piercing damage, Properties Thrown range 30/120ft.
Bonus Actions
Aggressive. As a bonus action, the creature can move up to its speed toward a hostile creature that it can see.
```

**Comment by meta5by5** [comment]
I sourced it from rpgTinker at first and then did some (very) heavy
editing. I rearranged a lot and tried variations (like your point about
Counterspell as two words at first, and then one word).

Thanks for the guidance. I'm trying to find a way to build custom
NPCs/monsters that calculate HP, damage, CR and such without building
everything from scratch.
